

name: auto-merge

# Controls when the workflow will run
on:

  pull_request_review:

jobs:

  auto-merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: kalgurn/merge-pr-action@1.0.0
        with:
          token: ${{ github.token }}
          owner: ${{ github.owner }}
          repo: ${{ github.repository }}
          pull_number: ${{ github.pull_number }}



