# This is a basic workflow to help you get started with Actions

name: issue-CI

# Controls when the workflow will run

on:
  issues:
    types: [opened]



jobs:

  auto-assign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: Auto Assign Issue
        uses: pozil/auto-assign-issue@v1
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            assignees: testuser01
